
#ifndef PROBLEMA1_CONFIG_H

#define PROBLEMA1_CONFIG_H

#define CANTIDAD_THREAD 20 // cantidad de procesos
#define SIZEDATETIME 128 //CONSTANTE PARA LAS CADENAS DE LA FECHA Y HORA DEL PROCESO

#endif // PROBLEMA1_CONFIG_H